# PSKR endpoint uses mojo and greatly benefits from the use of fastcgi

fastcgi.server = (
    "/ham/HamClock/fetchPSKReporter.pl" => ((
        "bin-path"        => "/opt/hamclock-backend/htdocs/ham/HamClock/fetchPSKReporter.pl",
        "socket"          => "/tmp/fetchPSKReporter.sock",
        "socket"          => "/run/lighttpd/fastcgi-pskr.sock",
        "check-local"     => "disable",
        "max-procs"       => 4, # Adjust based on your available CPU cores/burst sizes
        "fix-root-scriptname" => "enable"
    ))
)


