#!/usr/bin/env bash
# ============================================================
#
#   ██████╗ ██╗  ██╗██████╗
#  ██╔═══██╗██║  ██║██╔══██╗
#  ██║   ██║███████║██████╔╝
#  ██║   ██║██╔══██║██╔══██╗
#  ╚██████╔╝██║  ██║██████╔╝
#   ╚═════╝ ╚═╝  ╚═╝╚═════╝
#
#  Open HamClock Backend
#  fetch_sat_freq.sh
#
#  Copyright (C) 2026 Open HamClock Backend (OHB) Contributors
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# ============================================================
#
# Runs AFTER fetch_tle.sh / filter_amsat_active.pl.
#
# Reads the satellite list those scripts produced (esats.txt), looks up the
# transmitter list for each satellite in the SatNOGS DB (keyed by NORAD id),
# and writes a parallel frequency/mode file (esats-freq.txt) into the same
# web root, served to the client at /esats/esats-freq.txt.
#
# Output is a flat, comma-delimited table, one transmitter per line, grouped
# by NORAD. The client joins it to a displayed satellite on the NORAD id it
# already holds in TLE line 1. Lines beginning with '#' are comments.
#
#   norad,name,status,type,mode,uplink_low,uplink_high,downlink_low,downlink_high,baud,invert,ctcss,description
#
# All frequencies are in Hz exactly as SatNOGS reports them; *_high is blank
# for single-frequency (non-transponder) transmitters. Transmitters of every
# status except "invalid" are written; the "status" column (active / inactive /
# future) lets the client show or filter them. The description is the last
# field and has any commas (-> ";"), pipes, and newlines stripped so a naive
# split on "," stays correct.
#

set -euo pipefail

# --- Config (env-overridable, same convention as filter_amsat_active.pl) ---
ESATS_IN="${ESATS_OUT:-/opt/hamclock-backend/htdocs/ham/HamClock/esats/esats.txt}"
FREQ_OUT="${ESATS_FREQ_OUT:-/opt/hamclock-backend/htdocs/ham/HamClock/esats/esats-freq.txt}"

SATNOGS_API="${SATNOGS_API:-https://db.satnogs.org/api/transmitters/}"
HTTP_TIMEOUT="${HTTP_TIMEOUT:-20}"     # seconds per request
REQ_SLEEP="${REQ_SLEEP:-0.5}"          # polite delay between API calls, seconds
USER_AGENT="${USER_AGENT:-OHB-fetch_sat_freq/1.0 (+https://github.com/komacke/open-hamclock-backend)}"

ts() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
log() { echo "[$(ts)] $*" >&2; }

# --- Dependency check ---
for bin in curl jq; do
    command -v "$bin" >/dev/null 2>&1 || { log "ERROR: required tool '$bin' not found"; exit 1; }
done

[[ -r "$ESATS_IN" ]] || { log "ERROR: cannot read input $ESATS_IN"; exit 1; }
mkdir -p "$(dirname "$FREQ_OUT")"

TMP_OUT="$(mktemp "${FREQ_OUT}.XXXXXX")"
trap 'rm -f "$TMP_OUT"' EXIT

# --- Header ---
{
    echo "# esats-freq.txt - generated by fetch_sat_freq.sh at $(ts)"
    echo "# source: SatNOGS DB ($SATNOGS_API), keyed by NORAD id"
    echo "# fields: norad,name,status,type,mode,uplink_low,uplink_high,downlink_low,downlink_high,baud,invert,ctcss,description"
    echo "# frequencies in Hz; *_high blank unless a transponder passband; status one of active/inactive/future"
    echo "# ctcss is the FM access tone in Hz parsed from the description (CTCSS/PL), blank if none"
} > "$TMP_OUT"

# --- Read esats.txt as strict 3-line blocks (matches filter output) ---
mapfile -t LINES < "$ESATS_IN"

declare -A seen_norad=()
n_sats=0
n_tx=0
n_miss=0

i=0
n=${#LINES[@]}
while (( i < n )); do
    name="${LINES[i]}"
    # strip CR and surrounding whitespace
    name="${name%$'\r'}"
    name="${name#"${name%%[![:space:]]*}"}"
    name="${name%"${name##*[![:space:]]}"}"

    # skip blanks / comments / stray element lines; advance one line to resync
    if [[ -z "$name" || "$name" == \#* || "$name" =~ ^[12][[:space:]] ]]; then
        (( i++ )) || true
        continue
    fi

    l1="${LINES[i+1]:-}"; l1="${l1%$'\r'}"
    l2="${LINES[i+2]:-}"; l2="${l2%$'\r'}"

    # validate this is a real TLE block; if not, resync by one line
    if [[ ! "$l1" =~ ^1[[:space:]] || ! "$l2" =~ ^2[[:space:]] ]]; then
        (( i++ )) || true
        continue
    fi

    # NORAD id from line 1, same regex the perl filter uses
    norad="$(sed -E 's/^1[[:space:]]+([0-9]+).*/\1/' <<< "$l1")"
    i=$(( i + 3 ))

    [[ -n "$norad" ]] || { log "WARN: no NORAD parsed for '$name'"; continue; }
    [[ -z "${seen_norad[$norad]:-}" ]] || continue   # dedupe
    seen_norad[$norad]=1
    (( n_sats++ )) || true

    # --- Query SatNOGS for this NORAD ---
    url="${SATNOGS_API}?satellite__norad_cat_id=${norad}&format=json"
    if ! json="$(curl -fsSL --retry 3 --retry-delay 2 --max-time "$HTTP_TIMEOUT" \
                      -A "$USER_AGENT" "$url" 2>/dev/null)"; then
        log "WARN: SatNOGS query failed for $name (NORAD $norad)"
        (( n_miss++ )) || true
        sleep "$REQ_SLEEP"
        continue
    fi

    # Transform active transmitters into pipe-delimited rows.
    # tostring on a JSON null yields "" because of the "// """ guard upstream.
    rows="$(jq -r --arg norad "$norad" --arg name "$name" '
        if type == "array" then . else [] end
        | map(select(.status != "invalid"))
        | .[]
        | [ $norad,
            $name,
            (.status      // "" | tostring),
            (.type        // "" | tostring),
            (.mode        // "" | tostring),
            (.uplink_low  // "" | tostring),
            (.uplink_high // "" | tostring),
            (.downlink_low  // "" | tostring),
            (.downlink_high // "" | tostring),
            (.baud   // "" | tostring),
            (.invert // false | tostring),
            ( [ (.description // "") | capture("(?:CTCSS|PL)\\s*:?\\s*(?<t>[0-9]+(?:\\.[0-9]+)?)"; "i") ] | (.[0].t // "") ),
            ((.description // "") | tostring
                | gsub(","; ";") | gsub("[|\r\n]"; " ")
                | gsub(" +"; " ") | gsub("^ +| +$"; ""))
          ]
        | join(",")
    ' <<< "$json" 2>/dev/null || true)"

    if [[ -n "$rows" ]]; then
        printf '%s\n' "$rows" >> "$TMP_OUT"
        cnt="$(grep -c '' <<< "$rows")"
        n_tx=$(( n_tx + cnt ))
    else
        log "INFO: no transmitters for $name (NORAD $norad)"
    fi

    sleep "$REQ_SLEEP"
done

# --- Sanity check + atomic install ---
if (( n_tx == 0 )); then
    log "ERROR: no transmitters written; leaving existing $FREQ_OUT untouched"
    exit 1
fi

mv "$TMP_OUT" "$FREQ_OUT"
trap - EXIT
log "Wrote $n_tx transmitters for $n_sats satellites to $FREQ_OUT ($n_miss lookups failed)"
