name: Release with manage-ohb-docker.sh asset

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (e.g., v0.0.1)'
        required: true
        default: 'v0.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add tag to manager
        run: |
	 	  # Define asset names with the tag
          MGR_NAME="manage-ohb-docker-${{ github.event.inputs.tag_name }}.sh"
          TAR_NAME="OHB-${{ github.ref_name }}.tar.gz"
          ZIP_NAME="OHB-${{ github.ref_name }}.zip"
          
          # create a manager with version in the name and file
          sed 's/^\(OHB_MANAGER_VERSION=\).*$/\1${{ github.event.inputs.tag_name }}/' ./docker/manage-ohb-docker.sh \
          > "./docker/$MGR_NAME"

		  # create the tars and zips
          tar -czf "$TAR_NAME" .
          zip -r "$ZIP_NAME" .

      - name: Create Release and Upload Asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Grabs file from repo tree and uploads with a label
          gh release create ${{ github.event.inputs.tag_name }} \
            './docker/manage-ohb-docker-${{ github.event.inputs.tag_name }}.sh#Manage OHB Docker Installs' \
   			"my-project-${{ github.ref_name }}.tar.gz#OHB source tarball" \
            "my-project-${{ github.ref_name }}.zip#OHB source zip" \
            --title "OHB Release: ${{ github.event.inputs.tag_name }}" \
            --generate-notes
